dataset:
  clip_length: 180
  format: rgb
  label_path: ./datasets/PURE/gtdump.xmp
  name: PURE
  step: 30
  video_path: ./datasets/PURE/videos
model:
  dropout: 0.0
  frames: 180
  input_size:
  - 3
  - 36
  - 36
  name: physnet
  num_classes: 1
  sampling_rate: 30
output:
  save_dir: ./saved_models/physnet_PURE
training:
  batch_size: 4
  epochs: 50
  learning_rate: 0.001
  loss_fn: mse
  optimizer: adam
  shuffle: true
